[project]
name = "getcoursepythondownloader"
version = "0.1.0"
description = "Download video from GetCourse"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.11",
    "tqdm>=4.67.1",
]
[project.scripts]
getcourse = "gcpd:starter"
